set nocompatible

" Use pathogen for bundle management
call pathogen#infect()

" Set the best leader
let mapleader=","

" Set encoding
set encoding=utf-8

" Look and feel
set number
set ruler
syntax on

" Status bar
set laststatus=2

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Show (partial) command in the status line
set showcmd

" FuzzyFinder configuration
map <Leader>n :FufFileWithCurrentBufferDir<CR>
map <Leader>b :FufBuffer<CR>
map <Leader>t :FufBufferTag<CR>
