fpath=($fpath $HOME/.zsh/functions)
autoload -U $HOME/.zsh/functions/*(:t)

typeset -U fpath

export LS_OPTIONS='--color=auto'                                                                    
export CLICOLOR='Yes'
export LSCOLORS=''

export PATH=$PATH:/usr/local/mongodb/bin/

[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

. ~/.zsh/git_prompt
. ~/.zsh/completion
. ~/.zsh/bindings
